// Verdad o Reto +18 — niveles y contenido.
// {n} = un jugador al azar · {o} = otro jugador · {yo} = quien juega
import { pickPareja } from '../../lib/players';

export const NIVELES = [
  { id: 'suave', label: 'Suave', emoji: '😇', nivel: 1, desc: 'Para romper el hielo' },
  { id: 'atrevido', label: 'Atrevido', emoji: '😏', nivel: 2, desc: 'Sube la temperatura' },
  { id: 'loco', label: 'Loco', emoji: '🤪', nivel: 3, desc: 'Caos total' },
  { id: 'pareja', label: 'Pareja', emoji: '💑', nivel: 3, desc: 'Solo para dos' },
  { id: 'hardcore', label: 'Hardcore', emoji: '🔥', nivel: 4, desc: 'Sin vergüenza' },
  { id: '4play', label: '4Play', emoji: '🔞', nivel: 5, desc: 'Nivel dios' },
];

export const PROMPTS = {
  suave: {
    verdad: [
      '{n}, ¿cuál ha sido tu peor cita?',
      '{n}, ¿alguna vez has espiado el celular de tu pareja?',
      '{n}, ¿quién te parece más atractivo de esta sala?',
      '{n}, ¿cuál es el apodo más cursi que te han puesto?',
      '{n}, ¿te has enamorado de un amigo o amiga?',
      '{n}, ¿cuál es la mentira más tonta que has dicho para caer bien?',
      '{n}, ¿cuánto tiempo pasó tu relación más corta?',
      '{n}, ¿alguna vez le mandaste un mensaje y te arrepentiste al segundo?',
      '{n}, ¿qué canción te da vergüenza que sepan que te gusta?',
      '{n}, ¿cuál fue tu crush de la infancia?',
      '{n}, ¿te has hecho el dormido para no hablar con alguien?',
      '{n}, ¿stalkeaste hoy a alguien en redes? ¿a quién?',
      '{n}, ¿cuál es tu mayor inseguridad al conocer a alguien?',
      '{n}, ¿alguna vez fingiste que te gustaba un regalo?',
    ],
    reto: [
      '{n}, dale un abrazo de 20 segundos a {o}.',
      '{n}, imita cómo ligas y que el grupo puntúe.',
      '{n}, deja que {o} revise tu última búsqueda en el navegador.',
      '{n}, dile un piropo a {o} mirándole a los ojos sin reírte.',
      '{n}, manda un mensaje de "te extraño" al tercer chat de tu WhatsApp.',
      '{n}, habla con acento extranjero hasta tu próximo turno.',
      '{n}, deja que {o} te despeine como quiera.',
      '{n}, dile a {o} tres cosas que te caen bien de él o ella.',
      '{n}, haz tu mejor pose de foto y que {o} te tome una.',
      '{n}, canta el coro de la última canción que escuchaste.',
      '{n}, imita a alguien del grupo hasta que adivinen quién es.',
      '{n}, deja que el grupo elija tu foto de perfil por 10 minutos.',
      '{n}, cuéntale un secreto random al oído a {o}.',
    ],
  },
  atrevido: {
    verdad: [
      '{n}, ¿cuál es tu fantasía más recurrente?',
      '{n}, ¿con quién de esta sala te irías si pudieras?',
      '{n}, ¿qué es lo más atrevido que has hecho en público?',
      '{n}, del 1 al 10, ¿qué tan bueno eres en la cama?',
      '{n}, ¿alguna vez tuviste un amigo con derechos secreto?',
      '{n}, ¿cuál es tu zona favorita para que te besen?',
      '{n}, ¿te has arrepentido de acostarte con alguien justo después?',
      '{n}, ¿cuántas personas del grupo te parecen besables?',
      '{n}, ¿cuál es la excusa más falsa que has usado para no tener intimidad?',
      '{n}, ¿qué prenda tuya crees que es la más sexy?',
      '{n}, ¿has enviado un mensaje subido de tono a la persona equivocada?',
      '{n}, ¿mirarías a alguien de esta sala si te lo cruzaras en una app de citas?',
      '{n}, ¿cuál es tu mayor "sí" y tu mayor "no" en la intimidad?',
    ],
    reto: [
      '{n}, quítate una prenda (no zapatos ni calcetines).',
      '{n}, hazle un baile sensual a {o} durante 20 segundos.',
      '{n}, susúrrale algo subido de tono al oído de {o}.',
      '{n}, deja que {o} te dé un mordisco suave donde elija.',
      '{n}, siéntate en las piernas de {o} hasta tu próximo turno.',
      '{n}, dale un beso en la mejilla a cada persona del grupo.',
      '{n}, mira fijo a {o} durante 30 segundos sin reírte; si te ríes, otra prenda.',
      '{n}, deja que {o} escriba lo que quiera en tu brazo con lápiz labial o boli.',
      '{n}, describe con lujo de detalle tu cita perfecta con {o}.',
      '{n}, manda un audio diciendo "me gustas" y que el grupo elija a quién.',
      '{n}, deja que {o} te haga una pregunta íntima y respóndela con total sinceridad.',
      '{n}, recorre el cuello de {o} con un cubito de hielo (o el dedo frío).',
    ],
  },
  loco: {
    verdad: [
      '{n}, ¿cuál es la mentira más grande que has dicho para no quedar mal?',
      '{n}, ¿qué harías con 10.000 soles ahora mismo?',
      '{n}, cuenta la anécdota más vergonzosa de tu vida.',
      '{n}, ¿cuál es lo más raro que has hecho estando borracho?',
      '{n}, ¿alguna vez te descubrieron husmeando algo que no debías?',
      '{n}, ¿qué es lo más caro que has roto y no confesaste?',
      '{n}, ¿cuál es tu teoría conspirativa favorita?',
      '{n}, ¿qué app esconderías si te reviso el celular ahora?',
      '{n}, ¿cuál es el peor regalo que has dado?',
      '{n}, ¿alguna vez lloraste por algo ridículo? cuéntalo.',
      '{n}, ¿qué famoso te cae mal sin razón?',
      '{n}, ¿cuál es tu peor hábito que nadie sabe?',
    ],
    reto: [
      '{n}, habla como bebé hasta tu próximo turno.',
      '{n}, deja que el grupo te reescriba el estado de WhatsApp.',
      '{n}, llama a un contacto al azar y cántale "feliz cumpleaños".',
      '{n} y {o}, intercambien una prenda de ropa ahora.',
      '{n}, haz 10 sentadillas gritando el número en otro idioma.',
      '{n}, deja que {o} te maquille o peine con los ojos cerrados.',
      '{n}, publica una historia diciendo "extraño a mi ex" durante 5 minutos.',
      '{n}, imita a un animal hasta que el grupo adivine cuál.',
      '{n}, deja que el grupo elija un emoji y ponlo de nombre en el chat por 1 día.',
      '{n}, baila sin música 20 segundos como si fuera tu canción favorita.',
      '{n}, cuenta un chiste; si nadie se ríe, tomas o cumples otro reto.',
      '{n}, deja que {o} te haga una trenza, coleta o peinado ridículo.',
    ],
  },
  pareja: {
    verdad: [
      '{n}, ¿qué es lo que más te gusta que te hagan y nunca lo has pedido?',
      '{n}, ¿cuándo fue la última vez que deseaste a tu pareja de verdad?',
      '{n}, ¿hay algo que te gustaría probar y no te has atrevido a decir?',
      '{n}, ¿cuál fue el momento en que supiste que te gustaba {o}?',
      '{n}, ¿qué detalle pequeño de {o} te enamora?',
      '{n}, ¿cuál ha sido nuestro mejor beso hasta ahora?',
      '{n}, ¿qué te da más celos y nunca lo admites?',
      '{n}, ¿qué fantasía te gustaría cumplir con {o} este año?',
      '{n}, ¿en qué lugar raro te gustaría besarte con {o}?',
      '{n}, ¿qué canción te recuerda a {o}?',
      '{n}, ¿qué es lo primero que notaste físicamente de {o}?',
      '{n}, ¿qué harías si tuvieras a {o} solo por 24 horas sin planes?',
    ],
    reto: [
      '{n}, dale un beso a {o} como si fuera la primera vez.',
      '{n}, dile a {o} tres cosas que te encienden de él o ella.',
      '{n}, véndale los ojos a {o} y hazle adivinar 3 cosas por el tacto.',
      '{n}, mírale a los ojos a {o} durante un minuto en silencio.',
      '{n}, hazle un masaje de hombros a {o} durante 2 minutos.',
      '{n}, escríbele a {o} una nota de una línea y dásela.',
      '{n}, recrea con {o} la escena de película romántica que más te gusta.',
      '{n}, besa a {o} en tres lugares distintos, lento.',
      '{n}, dile a {o} al oído qué te gustaría hacer cuando lleguen a casa.',
      '{n}, deja que {o} elija tu próximo reto de este nivel.',
      '{n}, baila una canción lenta pegado a {o}.',
    ],
  },
  hardcore: {
    verdad: [
      '{n}, ¿has enviado fotos íntimas? ¿a quién fue la última?',
      '{n}, ¿cuál es el lugar más arriesgado donde lo has hecho?',
      '{n}, ¿has tenido un sueño húmedo con alguien de esta sala?',
      '{n}, nombra tu fetiche sin rodeos.',
      '{n}, ¿cuál es tu récord de veces en una noche?',
      '{n}, ¿alguna vez lo hiciste en casa ajena en una fiesta?',
      '{n}, ¿qué es lo más atrevido que te han pedido y aceptaste?',
      '{n}, ¿usas juguetes? ¿cuál es tu favorito?',
      '{n}, ¿a quién de esta sala elegirías para una noche sin consecuencias?',
      '{n}, ¿cuál es tu posición favorita y por qué?',
      '{n}, ¿alguna vez grabaste un video íntimo?',
      '{n}, ¿qué parte de tu cuerpo te gusta más que te toquen?',
      '{n}, ¿mensajeas caliente con alguien ahora mismo? sí o no.',
    ],
    reto: [
      '{n}, besa el cuello de {o} durante 10 segundos.',
      '{n}, pásale un cubo de hielo a {o} por donde el grupo diga.',
      '{n}, deja que {o} te quite una prenda usando solo los dientes.',
      '{n}, simula tu mejor cara de placer durante 5 segundos.',
      '{n}, dale a {o} un beso francés de 10 segundos.',
      '{n}, deja que {o} te dé un chupón donde no se vea con ropa.',
      '{n}, describe en voz alta lo que le harías a {o} si no hubiera nadie más.',
      '{n}, siéntate en las piernas de {o} de frente por dos turnos.',
      '{n}, muerde el labio de {o} suavemente.',
      '{n} y {o}, hagan la posición más comprometida que puedan sin quitarse ropa y aguántenla 15 segundos.',
      '{n}, deja que {o} te ate las manos con lo que encuentre por un turno.',
      '{n}, quítate dos prendas o reparte 3 castigos.',
    ],
  },
  '4play': {
    verdad: [
      '{n}, ¿estarías dispuesto a un trío con alguien de esta sala?',
      '{n}, ¿a quién de aquí te llevarías a la cama sin pensarlo?',
      '{n}, confiesa el pensamiento más sucio que has tenido hoy.',
      '{n}, ¿qué dos personas de esta sala pondrías juntas?',
      '{n}, ¿harías un intercambio de parejas por una noche?',
      '{n}, ¿cuál es tu límite absoluto que nunca cruzarías?',
      '{n}, si esta sala fuera una orgía, ¿te quedarías o te irías?',
      '{n}, ¿besarías a alguien de tu mismo sexo aquí ahora?',
      '{n}, ¿qué es lo más morboso que te gustaría que te hicieran delante de gente?',
      '{n}, elige: besar a {o} o quitarte toda la ropa por un turno.',
    ],
    reto: [
      '{n}, besa apasionadamente a {o} durante 10 segundos.',
      '{n}, siéntate en las piernas de {o} hasta tu próximo turno.',
      '{n}, deja que {o} escriba con el dedo una palabra en tu espalda y adivínala.',
      '{n}, dale un beso en el cuello a las dos personas a tus lados.',
      '{n} y {o}, intercambien una prenda de ropa delante de todos.',
      '{n}, elige a dos personas para que te den un masaje a la vez por 30 segundos.',
      '{n}, deja que el grupo elija a quién besas (mejilla o labios lo decide el grupo).',
      '{n}, haz un baile privado de 20 segundos para {o} mientras el grupo cuenta.',
      '{n}, quítate una prenda y dásela a {o} para que la use un turno.',
      '{n}, susúrrale a {o} al oído lo más atrevido que se te ocurra; {o} decide si lo repite en voz alta.',
    ],
  },
};

const rand = (arr) => arr[Math.floor(Math.random() * arr.length)];

export function buildPrompt(nivelId, tipo, jugadores) {
  const lista = PROMPTS[nivelId]?.[tipo] || PROMPTS.suave[tipo];
  const text = rand(lista);
  const [n, o] = pickPareja(jugadores, tipo === 'reto');
  return text.replaceAll('{n}', n).replaceAll('{o}', o).replaceAll('{yo}', n);
}

// Total de prompts cargados por nivel (para la vista de contenido)
export const contentStats = () =>
  NIVELES.map((nv) => ({
    ...nv,
    verdad: PROMPTS[nv.id]?.verdad?.length || 0,
    reto: PROMPTS[nv.id]?.reto?.length || 0,
  }));
